//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab7MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderr
    {
        public string OrderID { get; set; }
        public string OrderDate { get; set; }
        public string AgentID { get; set; }
    }
}
